name: code_union_localization
description: This package contains localization.

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  slang: ^3.19.0
  slang_flutter: ^3.19.0

dev_dependencies:
  my_lints:
    git:
      url: https://github.com/birimkulov951/my_lints
  build_runner: ^2.4.5
  slang_build_runner: ^3.7.0